server:
  port: 8002

spring:
  datasource:
    url: 'jdbc:postgresql://postgresql:5432/inventography?currentSchema=inventory'
    username: 'postgres'
    password: '12345'
    hikari:
      connection-test-query: SELECT 1;
      connection-timeout: 30000
      driver-class-name: org.postgresql.Driver
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 1
      validation-timeout: 28000
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: "Asia/Jakarta"
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: 'bitnami-kafka:9092'
logging:
  file:
    path: "build/logs/"
    name: "inventory.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB
