server:
  port: 8001

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/inventography?currentSchema=ordering'
    username: 'postgres'
    password: '12345'
    hikari:
      connection-test-query: SELECT 1;
      connection-timeout: 30000
      driver-class-name: org.postgresql.Driver
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 1
      validation-timeout: 28000
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
logging:
  file:
    name: "build/logs/order.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB
